Repository javascript-code-study/javascript-code-study, pull requests merged in 2025-08, with the labels that each got.

#38 week10 - 브루트포스(재귀)
  KimDohee/week10/로또.js
  KimDohee/week10/부분수열의 합.js
  KimDohee/week10/연산자 끼워넣기(2).js
Labels: 실버2

#40 week11 - 브루트포스(재귀)
  jincheol/week11/input1.txt
  jincheol/week11/input2.txt
  jincheol/week11/input3.txt
  jincheol/week11/personal-bruteForce.js
  jincheol/week11/study-bruteForce1.js
  jincheol/week11/study-bruteForce2.js
Labels: 실버3, 실버1, 골드4

#42 week1 - 브루트포스(재귀)
  KimSuyeon/week1/GatheringEnergy.js
  KimSuyeon/week1/Resignation.js
  KimSuyeon/week1/input1.txt
  KimSuyeon/week1/input2.txt
Labels: 실버3, 실버1

#50 week3 - BFS(연습)
  KimSuyeon/week3/CountLand.js
  KimSuyeon/week3/Fout.js
  KimSuyeon/week3/Maze.js
  KimSuyeon/week3/SnakeAndLeader.js
  KimSuyeon/week3/Virus.js
  KimSuyeon/week3/input1.txt
  KimSuyeon/week3/input2.txt
  KimSuyeon/week3/input3.txt
  KimSuyeon/week3/input4.txt
  KimSuyeon/week3/input5.txt
Labels: 실버2, 실버3, 실버1, 골드4, 골드5
